json_tokener: fix the following errors
    /home/btibi/new_home/workspace/syslog-ng-ose-3.8/json-c/json_tokener.c:
In function 'json_tokener_parse_ex':
    /home/btibi/new_home/workspace/syslog-ng-ose-3.8/json-c/json_tokener.c:201:36:
error: right-hand operand of comma expression has no effect
[-Werror=unused-value]
       ( ++(str), ((tok)->char_offset)++, c)
                                        ^
    /home/btibi/new_home/workspace/syslog-ng-ose-3.8/json-c/json_tokener.c:467:14:
note: in expansion of macro 'ADVANCE_CHAR'
                  ADVANCE_CHAR(str, tok);
                  ^
    /home/btibi/new_home/workspace/syslog-ng-ose-3.8/json-c/json_tokener.c:201:36:
error: right-hand operand of comma expression has no effect
[-Werror=unused-value]
       ( ++(str), ((tok)->char_offset)++, c)
                                        ^
    /home/btibi/new_home/workspace/syslog-ng-ose-3.8/json-c/json_tokener.c:468:14:
note: in expansion of macro 'ADVANCE_CHAR'
                  ADVANCE_CHAR(str, tok);

Fix-proposed-by: Tamas Nagy <tamas.nagy@balabit.com>
Signed-off-by: Tibor Benke <tibor.benke@balabit.com>